catalogo_peliculas = {                          
    "acción": ["Mad Max","John Wick","Misión Imposible","Alerta Roja","Gladiador","Avengers: Endgame",
               "Avengers: Infinity War"],
    "terror": ["El Conjuro", "It", "Annabelle","La monja","La noche del demonio","It: Capítulo 2","Saw"],
    
    "comedia": ["Superbad","Step Brothers","Ted","Proyecto X","Son como niños","¿Qué pasó ayer?"],

    "romance": ["Titanic","El diario de una pasión","La La Land","Orgullo y prejuicio","Yo antes de ti"]
}

catalogo_series = {
    "acción": ["The Boys", "Vikings", "Daredevil", "The Punisher", "Arrow", "24", "The 100"],
    
    
    "terror": ["Stranger Things", "The Haunting of Hill House", "Marianne", "Chucky", "American Horror Story"],
    
    
    "comedia": ["The Office", "Brooklyn Nine-Nine", "Friends", "Parks and Recreation", "How I Met Your Mother"],
    
    
    "romance": ["Emily in Paris", "Bridgerton", "Outlander", "Jane the Virgin", "Virgin River"]
}

# Reseñas de películas y series 
reseñas= {
    #peliculas
    "Mad Max": "Aunque está decidido a vagar solo por el páramo post-apocalíptico, Mad Max se une a Furiosa, una comandante fugitiva, y su banda, quienes están tratando de escapar de un señor de la guerra.",
    "John Wick":"La ciudad de Nueva York se llena de balas cuando John Wick, un exasesino a sueldo, enfrenta a los mafiosos rusos que destruyeron todo aquello que él amaba y pusieron precio a su cabeza.",
    "Misión Imposible":"Hunt y su equipo se lanzan a una operación contrarreloj para encontrar a la Entidad, una inteligencia artificial sin escrúpulos con el potencial de destruir a la humanidad.",
    "Alerta Roja": "John Hartley, agente de la Interpol, no tendrá otro remedio que aliarse con el ladrón de arte más célebre de todos los tiempos, Nolan Booth, para capturar a la ladrona de arte más buscada del presente: la seductora y peligrosa Sarah Black.",
    "Gladiador": "Máximo, general romano, desea volver a casa, pero el emperador Marco Aurelio quiere que herede el imperio. Esto hace que Cómodo ordene matar a su familia. Máximo escapa de la muerte y regresa a Roma como gladiador para vengar la muerte de su familia.",
    "Avengers: Endgame": "Los Vengadores comprenden por fin lo frágil que es la realidad y los sacrificios que hay que hacer para mantenerla, en una historia de amistad, trabajo en equipo y sobre dejar a un lado las diferencias para superar un obstáculo imposible.",
    "Avengers: Infinity War":"Los superhéroes se alían para vencer al poderoso Thanos, el peor enemigo al que se han enfrentado. Si Thanos logra reunir las seis gemas del infinito: poder, tiempo, alma, realidad, mente y espacio, nadie podrá detenerlo.",
    "El Conjuro":"A principios de los años 70, Ed y Lorrain Warren, reputados investigadores de fenómenos paranormales, se enfrentan a una entidad demoníaca al intentar ayudar a una familia que está siendo aterrorizada por una presencia oscura en su aislada granja.", 
    "It":"Varios niños de una pequeña ciudad del estado de Maine se alían para combatir a una entidad diabólica que adopta la forma de un payaso y desde hace mucho tiempo emerge cada 27 años para saciarse de sangre infantil.", 
    "Annabelle":"Una mujer embarazada, Mia, recibe una muñeca antigua como regalo de su esposo, John. Tras ser atacados por los integrantes de un culto satánico, la pareja comienza a sufrir la influencia maligna del ser que posee a la muñeca Annabelle.",
    "La noche del demonio":"Josh y Renai se mudan a una nueva casa, donde su hijo tiene un terrible accidente y queda en estado de coma.",
    "It: Capítulo 2":"En el misterioso pueblo de Derry, un payaso llamado Pennywise vuelve 27 años después para atormentar a los ahora adultos miembros del Club de los Perdedores, que se encuentran alejados unos de otros.",
    "La monja":"Una monja se suicida en una abadía rumana y el Vaticano envía a un sacerdote y una novicia a investigar lo sucedido. Lo que ambos encuentran allá es un secreto perverso que los enfrentará cara a cara con el mal en su esencia más pura.",
    "Saw":"Adam y Lawrence se despiertan encadenados en un baño infecto con un cadáver entre ellos. Su secuestrador es un maniaco, cuyo juego consiste en forzar a sus cautivos a herirse a sí mismos o a otros para permanecer vivos.", 
    "Superbad":"La ansiedad por la separación representa un problema para dos jóvenes estudiantes de último año de preparatoria, que esperan divertirse y conseguir chicas hermosas en su fiesta de graduación.",
    "Step Brothers":"Brennan Huff y Dale Doback tienen una cosa en común: ambos son flojos, están desempleados y aún viven con sus padres. Cuando la madre de Brennan y el padre de Dale se casan y empiezan a vivir juntos, el mundo de los chicos se transforma totalmente. Su enfermiza rivalidad y narcisismo amenazan con separar a la nueva familia, lo que obliga a Brennan y a Dale a trabajar juntos para reunir a sus padres.",
    "Ted":"Cuando John Bennett era un niño pequeño, pidió el deseo de que Ted, su querido oso de peluche, cobrara vida. Treinta años más tarde, Ted continúa siendo el compañero de John, ante el disgusto de Lori, la novia de John. Aunque el disgusto de Lori se ve agravado por el constante consumo de la pareja de cerveza y marihuana, ella no es quien está más decepcionada con John; ya que puede necesitar la intervención del juguete de John para hacerlo madurar.",
    "Proyecto X":"Tres estudiantes de secundaria deciden organizar una fiesta salvaje en casa de uno de ellos, aprovechando que sus padres no están. Quieren hacer que la fiesta sea inolvidable, así que deciden grabarlo todo. Parece que la fiesta es todo un éxito: todo el mundo está bebiendo y los ánimos están por los aires. Sin embargo, una serie de complicaciones imprevistas harán que la fiesta se descontrole.",
    "Son como niños":"Un grupo de amigos y excompañeros descubren que envejecer no siempre significa madurar cuando se reúnen para honrar la memoria de su entrenador de baloncesto.",
    "¿Qué pasó ayer?":"Dos días antes de su boda, Doug y tres amigos viajan a Las Vegas para una fiesta inolvidable y salvaje. De hecho, cuando los tres acompañantes despiertan la mañana siguiente, no recuerdan nada ni encuentran a Doug. Con poco tiempo por delante, los tres amigos intentan recordar sus pasos y encontrar a Doug para que regrese a Los Ángeles para su boda.",
    "Titanic":"Una joven de la alta sociedad abandona a su arrogante pretendiente por un artista humilde en el trasatlántico que se hundió durante su viaje inaugural.",
    "El diario de una pasión":"En un hogar de retiro un hombre le lee a una mujer, que sufre de Alzheimer, la historia de dos jóvenes de distintas clases sociales que se enamoraron durante la convulsionada década del 40, y de cómo fueron separados por terceros, y por la guerra.",
    "La La Land":"Sebastian, un pianista de jazz, y Mia, una aspirante a actriz, se enamoran locamente; pero la ambición desmedida que tienen por triunfar en sus respectivas carreras, en una ciudad como Los Ángeles, repleta de competencia y carente de piedad, pone en peligro su amor.",
    "Orgullo y prejuicio":"Elizabeth Bennet conoce al apuesto y adinerado Sr. Darcy, con quien, rápidamente, inicia una intensa y compleja dinámica.",
    "Yo antes de ti":"La vida de Louisa Clark, una chica alegre y alocada, que va empalmando un trabajo con otro para ayudar a su familia a subsistir, cambia por completo cuando comienza a trabajar como cuidadora de un joven millonario, quien quedó paralítico tras un accidente. Poco a poco, se va estableciendo entre ellos una conexión cada vez más íntima.",
    #series:
    "The Boys":"Cuando los superhéroes abusan de sus superpoderes en lugar de usarlos para el bien, unos 'muchachos' se embarcan en una búsqueda heroica para exponer sus secretos.",
    "Vikings":"El vikingo Ragnar Lothbrok es un joven agricultor y hombre de familia que se siente frustrado por las políticas de Earl Haraldson, el conde del lugar que envía a sus invasores vikingos al este de los países bálticos y Rusia, cuyos residentes son pobres como los escandinavos. Ragnar prefiere ir al oeste, al otro lado del océano, para descubrir nuevas civilizaciones. Con la ayuda de su amigo Floki, Ragnar construye una flota de barcos que lo ayudará a alcanzar el mundo occidental. A través de los años Ragnar, que dice ser un descendiente directo del dios Odín, continúa luchando con Earl hasta que los dos se enfrentan en la última batalla por la supremacía.",
    "Daredevil":"Ciego desde que era joven, Matt Murdock lucha contra la injusticia de día como abogado y por la noche como Daredevil en Nueva York.",
    "The Punisher":"Un exmarine se ve envuelto en una conspiración militar mientras trata de castigar a las personas responsables de los asesinatos de los miembros de su familia.",
    "Arrow":"Cuando Oliver Queen, un billonario mujeriego, que se presumía había fallecido, regresa a casa a la ciudad Starling, luego de cinco años de quedar atrapado en una isla remota en el Pacífico, él esconde los cambios creados por la experiencia en sí mismo, mientras busca la reconciliación con su ex Laurel; él secretamente lleva dos vidas paralelas, en el día actúa como el filántropo descomplicado que solía ser y en la noche saca a relucir su ego alterno como Arrow. Este personaje es una clase de super héroe que trata de corregir los errores de su familia y restaurar la gloria que tenía la ciudad previamente, su misión se complica por el padre de Laurel, quien es el detective Quentin Lance y está determinado a poner al vigilante en la cárcel.",
    "24":"El agente de contra terrorismo, Jack Bauer, lucha contra los hombres malos en el mundo. Cada episodio semanal despliega en tiempo real las 24 horas de un día en la vida de Bauer en cada temporada. Jack enfrenta intentos de asesinato, ataques nucleares, bioterrorismo, la tortura, traidores, células terroristas y la tendencia a que sus romances terminen mal.",
    "The 100":"Un apocalipsis nuclear destruye la vida humana en la Tierra. Los únicos supervivientes son los habitantes de las estaciones espaciales internacionales. Tres generaciones después, la escasez de recursos los obliga a tomar medidas desesperadas.",
    "Stranger Things":"Cuando un niño desaparece, sus amigos, la familia y la policía se ven envueltos en una serie de eventos misteriosos al tratar de encontrarlo. Su ausencia coincide con el avistamiento de una criatura terrorífica y la aparición de una extraña niña.",
    "The Haunting of Hill House":"Veinte años después, debido a una tragedia, un grupo de hermanos regresa con su padre a la casa embrujada donde crecieron y en la que se suicidó su madre. ¿O acaso no fue un suicidio?",
    "Marianne":"Una famosa escritora vuelve a su ciudad natal y descubre que el espíritu maligno que invade sus sueños está causando estragos en el mundo real.",
    "Chucky":"Cuando un muñeco antiguo de Chucky aparece en una venta de jardín de los suburbios, una idílica ciudad estadounidense se ve sumida en el caos.",
    "American Horror Story":"American Horror Story fue creada por los co productores de Glee, pero los programas tienen poco en común, a parte de eso. El programa se enfoca en los Harmon, una familia de tres que se muda de Boston a Los Ángeles con el fin de superar los incidentes de su pasado. Lo que los Harmon no saben es que la casa en la que se han mudado está encantada, pero no está ocupada por Gasparín y sus amigos amables, está encantada por entidades demoniacas. Los fantasmas tienen una historia no solamente de asustar a los residentes de la casa pero también de desvanecerlos. Luego de estar viviendo en esta casa, el patriarca de la familia, Ben, quien es un psiquiatra puede que llegue a necesitar un psiquiatra para él mismo.",
    "The Office":"La adaptación de Estados Unidos, localizada en Scranton, Pensilvania., es la de una compañía papelera de alguna forma un poco más dinámica que la versión original Británica, aunque los personajes son esencialmente los mismos, desde Michael Scott, el peor jefe de todos hasta un hombre cualquiera Jim, enamorado de la recepcionista Pam a quien él le coquetea cuando no está preocupado por atormentar a su compañero Dwight, un hombre muy excitable y adulón.",
    "Brooklyn Nine-Nine":"Los detectives Jake Peralta, Amy Santiago, Rosa Diaz, Charles Boyle y el sargento Terry Jeffords forman una simpática y poco convencional brigada, pero todo cambia tras la llegada del nuevo jefe, el inflexible Raymond Holt.",
    "Friends":"Las aventuras de seis jóvenes neoyorquinos unidos por su amistad. En Central Perk, su café favorito, comparten sus alegrías y preocupaciones entre el amor, el trabajo y la familia.",
    "Parks and Recreation":"Leslie Knope, es una burócrata de nivel medio en el departamento de parques y recreación de Indiana, que tiene la esperanza de embellecer la ciudad y también mejorar su carrera, ayudando a una enfermera local llamada Ann Logan para transformar un lugar de construcción abandonado en un parque comunitario, pero lo que debía ser un proyecto simple se complica al ser obstaculizado en cada acción por burócratas zafios, vecinos egoístas, innumerables trámites gubernamentales y un sinnúmero de retos. Tom Haverford, el colega de Leslie que disfruta explotando su posición para beneficio propio, está dispuesto a bloquear sus esfuerzos en vez de ayudarla, mientras su jefe, Ron Swanson, se opone rotundamente a cualquier forma de gobierno aunque él sea un burócrata.",
    "How I Met Your Mother":"Ted se ha enamorado. Todo comenzó cuando su mejor amigo, Marshall confiesa que planea proponerle matrimonio a su novia de muchos años Lily, una profesora del jardín infantil. De repente, Ted se da cuenta que tiene tomar acción para encontrar el amor verdadero. Ayudándole en su búsqueda está Barney, un amigo incondicional y frecuentemente alocado en sus opiniones, en sus elecciones para el vestuario y su forma infalible de conocer mujeres. Cuando Ted conoce a Robin, está seguro de haberse enamorado a primera vista pero su romance se transforma en una amistad, la voz de Bob Saget (Full House) relata la historia a través de recuerdos.",
    "Emily in Paris":"Emily Cooper, una joven ejecutiva de marketing de Chicago, es contratada para proporcionar una perspectiva estadounidense en una empresa de marketing en París.",
    "Bridgerton":"Ocho hermanos de la poderosa familia Bridgerton intentan encontrar el amor y la felicidad de la alta sociedad londinense.",
    "Outlander":"Luego de servir como enfermera del Ejército británico en la Segunda Guerra Mundial, Claire Randall disfruta de una segunda luna de miel en Escocia con su esposo, pero de repente es transportada a 1743, donde se ven amenazadas su libertad y su vida.",
    "Jane the Virgin":"Una mujer de 23 años que estudia para maestra ha decidido permanecer virgen hasta el matrimonio, pero una visita de rutina al hospital cambia su vida, al ser inseminada accidentalmente. Ahora deberá enfrentar complicadas decisiones por su embarazo.",
    "Virgin River":"Una enfermera se muda de Los Ángeles a una remota ciudad del norte de California y se sorprende de lo que encuentra."
}
